BEGIN TRANSACTION;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100),
  age BIGINT DEFAULT 0,
  pet VARCHAR(100) DEFAULT '',
  email TEXT UNIQUE NOT NULL,
  entries BIGINT DEFAULT 0,
  joined TIMESTAMP NOT NULL
);

COMMIT;
